### ISSUE TITLE
Corpus alignment

### ISSUE THREAD

**Issue by Bachstelze** [danielinux7/Abkhaz-NLP-Data-Pipeline#106]
There are possible multilingual alignments pivot the ab-ru parallel corpus for the bible, human rights declaration and the Quran. [The Johns Hopkins University Bible Corpus: 1600+ Tongues for Typological Exploration](https://aclanthology.org/2020.lrec-1.352.pdf) and [The eBible Corpus: Data and Model Benchmarks for Bible Translation for Low-Resource Languages](https://arxiv.org/pdf/2304.09919.pdf) probably aligned the new testament with other parallel bibles. Though I couldn't find publicy if Abkhaz is really included.

**Comment by Bachstelze** [comment]
I got a reponse that asks for a file in USFM:
"As another alternative – if you have the original source files for the Abhkaz and Russian NT translations, and they are in USFM format, our tools could run over them using that format.  The output would be files that are lined up to match each of the other translations in the eBible corpus."

**Comment by danielinux7** [comment]
Hello Kalle,
The links to the original sources in Abkhazian can be found here:
https://github.com/danielinux7/Abkhaz-NLP-Data-Pipeline/blob/master/data/ab-ru/references.md (2,4 and 14)
I should assume they have a Russian version in USFM format included.

**Comment by Bachstelze** [comment]
I couldn't find a tool to convert the USFM format.

**Comment by danielinux7** [comment]
I am going to close issue then.
